name: pre-release
on:
  workflow_call:
    inputs:
      versionid:
        description: 'The version ID of the pre-release'
        required: true
        type: string
jobs:
  publish-pre-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - run: echo 'The triggering workflow passed, building a pre-release'
      - uses: actions/checkout@v3
      - name: Restore build from cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}\bin
            ${{ github.workspace }}\Support\Key2Joy.Tests\bin\Key2Joy.Tests
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Archive Pre-release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: 'bin\Key2Joy.Gui\Release'
          filename: 'pre-release.zip'
      - name: Create GitHub Pre-release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ inputs.versionid }}
          tag: ${{ inputs.versionid }}
          prerelease: true
          generateReleaseNotes: true
          artifacts: 'pre-release.zip'
          body: |
            # 🔧 ${{ inputs.versionid }}
            This release was automatically generated based on the last successful test run.

            This version of Key2Joy is not ready for use, but can be used for testing purposes.
