name: test
on:
  workflow_call:
jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - run: echo 'The triggering workflow passed, testing it'
      - uses: actions/checkout@v3
      - name: Setup .NET CLI
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Restore build from cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}\bin
            ${{ github.workspace }}\Support\Key2Joy.Tests\bin\Key2Joy.Tests
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Run Key2Joy Tests
        run: dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat="lcov" /p:CoverletOutput="${{ github.workspace }}/coverage/lcov.info"
      - name: Coveralls for Key2Joy
        uses: coverallsapp/github-action@v2
